Repository umbraco/OurUmbraco, pull requests merged in 2018-03, with the labels that each got.

#167 Fix up Gitter intergration
  OurUmbraco.Site/Assets/js/gitter/gitter.signalr.js
  OurUmbraco.Site/Assets/js/lib/emojione.min.js
  OurUmbraco.Site/OurUmbraco.Site.csproj
  OurUmbraco.Site/Views/Partials/Community/Gitter.cshtml
  OurUmbraco/Community/People/PeopleService.cs
  OurUmbraco/Gitter/GitterRoomSurfaceController.cs
  OurUmbraco/Gitter/GitterUmbracoEventHandler.cs
  OurUmbraco/Gitter/UmbracoMessage.cs
Labels: bug, feature

#168 Switch documentation Markdown conversion to use Markdig
  OurUmbraco.Client/src/scss/pages/_documentation.scss
  OurUmbraco.Site/OurUmbraco.Site.csproj
  OurUmbraco.Site/packages.config
  OurUmbraco/Documentation/Busineslogic/MarkdownLogic.cs
  OurUmbraco/OurUmbraco.csproj
  OurUmbraco/packages.config
Labels: enhancement

#191 Radar - bleep bloop beep
  OurUmbraco.Site/Views/Partials/Community/Map.cshtml
  OurUmbraco.Site/Views/Partials/Members/Profile.cshtml
  OurUmbraco/Community/Map/MapEventHandler.cs
  OurUmbraco/Community/Map/RadarHangfireJobs.cs
  OurUmbraco/Our/GoogleOAuth/UmbracoStandardOwinStartup.cs
  OurUmbraco/OurUmbraco.csproj
  OurUmbraco/packages.config
Labels: feature

#203 Updated codeshare logo
  OurUmbraco.Site/config/CommunityBlogs.json
Labels: UI
